In [1]:
# importing the dependencies
import numpy as np
import pandas as pd

In [3]:
#Load dataet
credit_card_data = pd.read_csv('..\SampleData\credit_data.csv')

<>:2: SyntaxWarning: invalid escape sequence '\S'
<>:2: SyntaxWarning: invalid escape sequence '\S'
C:\Users\prasa\AppData\Local\Temp\ipykernel_15084\4157161713.py:2: SyntaxWarning: invalid escape sequence '\S'
  credit_card_data = pd.read_csv('..\SampleData\credit_data.csv')

In [8]:
credit_card_data.head()
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [9]:
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [10]:
#above is highly imbalacned Data set - 0 Legit 1 means fradulant
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [11]:
print(legit.shape)

(284315, 31)

Under Sampling VVIP

In [12]:
#Under smapling - Building sample DS - similar distribution of legit and Fraud

legit_sample = legit.sample(n=492)

In [13]:
print(legit_sample.shape)

(492, 31)

In [14]:
new_dataset = pd.concat([legit_sample, fraud], axis = 0)

In [15]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
281973,170573.0,1.986161,-0.322584,-0.414636,0.367806,-0.342154,-0.007799,-0.574152,-0.017019,1.244785,...,0.202296,0.880401,0.128475,0.666620,-0.027152,-0.241165,0.049248,-0.027948,9.99,0
58331,48334.0,1.117884,-2.307230,-0.519766,-1.927522,0.131479,4.241714,-1.989942,1.032255,-0.807346,...,-0.108511,-0.128090,-0.277874,1.048507,0.592211,0.006465,0.055089,0.053013,205.59,0
101557,67876.0,-1.435357,-0.166031,2.965431,0.897819,-0.708058,0.616919,0.531285,0.348539,0.573895,...,-0.043609,-0.076555,0.231140,0.606101,0.495970,-0.503405,0.056991,0.097015,178.00,0
254631,156830.0,2.094479,-1.108800,-0.593249,-0.971453,-0.965019,-0.064280,-1.174867,0.133873,-0.056723,...,0.377681,1.056302,0.164729,0.726883,-0.203599,-0.137507,-0.001035,-0.050235,24.99,0
398,288.0,1.268069,0.285832,-0.147276,1.047742,0.672115,0.656656,0.138315,-0.010785,0.158271,...,-0.177627,-0.189526,-0.251549,-1.266236,0.901899,-0.230845,0.048271,0.004764,6.54,0

In [16]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64